# Generated by Django 5.1.3 on 2025-06-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('weekly_games', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('preset', models.JSONField(default=dict)),
                ('adocReady', models.BooleanField(default=False)),
                ('htmlReady', models.BooleanField(default=False)),
                ('pdfReady', models.BooleanField(default=False)),
                ('name', models.TextField(default='Untitled')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-market'],
                'constraints': [models.UniqueConstraint(fields=('market', 'name'), name='network_market_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espnid', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('displayName', models.CharField(max_length=100)),
                ('shortDisplayName', models.CharField(max_length=100)),
                ('tricode', models.CharField(max_length=10)),
                ('logo', models.URLField(null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='schedulemaker.league')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espnid', models.BigIntegerField(unique=True)),
                ('start', models.DateTimeField()),
                ('timevalid', models.BooleanField(default=True)),
                ('awayscore', models.SmallIntegerField()),
                ('homescore', models.SmallIntegerField()),
                ('gameover', models.BooleanField()),
                ('seasontype', models.SmallIntegerField()),
                ('week', models.SmallIntegerField(null=True)),
                ('networks', models.ManyToManyField(related_name='games', to='schedulemaker.network')),
                ('awayteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamesasaway', to='schedulemaker.team')),
                ('hometeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamesashome', to='schedulemaker.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('espnid', 'league'), name='team_espnid_league_unique'),
        ),
    ]
