# Generated by Django 5.1.3 on 2025-06-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='awayscore',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homescore',
            field=models.SmallIntegerField(null=True),
        ),
    ]
