# Generated by Django 5.1.3 on 2025-06-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['start']},
        ),
    ]
