# Generated by Django 5.1.3 on 2025-06-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0002_game_awayscore_game_homescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('preset', models.JSONField()),
            ],
        ),
    ]
