# Generated by Django 5.1.3 on 2025-06-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0002_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_have_bye',
            field=models.BooleanField(default=False),
        ),
    ]
