# Generated by Django 5.1.3 on 2025-06-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0003_team_can_have_bye'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
