# Generated by Django 5.1.3 on 2025-06-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='htmlReady',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pdfReady',
            field=models.BooleanField(default=False),
        ),
    ]
