# Generated by Django 5.1.3 on 2025-06-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0004_schedule_htmlready_schedule_pdfready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-market']},
        ),
    ]
