# Generated by Django 5.1.3 on 2025-06-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0005_alter_network_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.TextField(default='Untitled'),
        ),
    ]
