# Generated by Django 5.1.3 on 2025-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0006_schedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='preset',
            field=models.JSONField(default=dict),
        ),
    ]
