# Generated by Django 5.1.3 on 2025-06-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0007_alter_schedule_preset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='utcstart',
            new_name='start',
        ),
    ]
