# Generated by Django 5.1.3 on 2025-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0008_rename_utcstart_game_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='adocReady',
            field=models.BooleanField(default=False),
        ),
    ]
