# Generated by Django 5.1.3 on 2025-06-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0009_schedule_adocready'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameover',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='seasontype',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='awayscore',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='espnid',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='homescore',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
