# Generated by Django 5.1.3 on 2025-06-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaker', '0010_game_gameover_game_season_game_seasontype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
    ]
